import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import {
  Bell,
  CheckCheck,
  Trash2,
  RefreshCw,
  AlertCircle,
  Info,
} from 'lucide-react'
import toast from 'react-hot-toast'
import { motion, AnimatePresence } from 'framer-motion'

import { notificationAPI } from '@/api/sportsAPI'
import { useAuthStore } from '@/store/authStore'
import { Card, PageHeader, Button, Badge } from '@/components/ui'
import { smartNotificationAPI  }    from '../../api/sportsAPI'
import { Sparkles } from 'lucide-react'

export default function Notifications() {
  const userId = useAuthStore((s) => s.getUserId())
  const queryClient = useQueryClient()

  const { data, isLoading, refetch, isFetching } = useQuery({
    queryKey: ['notifications', userId],
    queryFn: () => notificationAPI.getAll(userId).then((res) => res.data),
    enabled: !!userId,
  })

  const markReadMutation = useMutation({
    mutationFn: (id) => notificationAPI.markRead(id),
    onSuccess: () => {
      toast.success('Notification marked as read')
      queryClient.invalidateQueries({ queryKey: ['notifications', userId] })
    },
  })

  const deleteMutation = useMutation({
    mutationFn: (id) => notificationAPI.delete(id),
    onSuccess: () => {
      toast.success('Notification deleted')
      queryClient.invalidateQueries({ queryKey: ['notifications', userId] })
    },
  })

  const notifications = data?.notifications || []

  const getPriorityVariant = (priority) => {
    if (priority === 'High') return 'danger'
    if (priority === 'Medium') return 'warning'
    if (priority === 'Low') return 'success'
    return 'gray'
  }

  const getIcon = (type) => {
    if (type?.toLowerCase().includes('risk')) return AlertCircle
    return Info
  }
  const generateSmartMutation = useMutation({
  mutationFn: () => smartNotificationAPI.generate(userId),
  onSuccess: () => {
    toast.success('Smart notifications generated')
    refetch()
  },
  onError: (err) => {
    toast.error(err.response?.data?.detail || 'Failed to generate smart notifications')
  },
})

  return (
    <div>
        <PageHeader
  title="Notifications"
  subtitle="Track alerts, AI insights and system updates."
  action={
    <div className="flex gap-3">
      <Button
        variant="secondary"
        onClick={() => generateSmartMutation.mutate()}
        loading={generateSmartMutation.isPending}
      >
        <Sparkles className="h-4 w-4" />
        Generate AI Alerts
      </Button>

      <Button onClick={() => refetch()} loading={isFetching}>
        <RefreshCw className="h-4 w-4" />
        Refresh
      </Button>
    </div>
  }
/>
      

      <div className="mb-8 grid gap-4 md:grid-cols-3">
        <Card hover={false}>
          <div className="flex items-center gap-4">
            <div className="rounded-2xl bg-primary/20 p-3 text-primary">
              <Bell className="h-6 w-6" />
            </div>

            <div>
              <p className="text-sm text-gray-400">Total Notifications</p>
              <h2 className="text-3xl font-black">
                {data?.total_notifications ?? 0}
              </h2>
            </div>
          </div>
        </Card>

        <Card hover={false}>
          <div className="flex items-center gap-4">
            <div className="rounded-2xl bg-warning/20 p-3 text-warning">
              <AlertCircle className="h-6 w-6" />
            </div>

            <div>
              <p className="text-sm text-gray-400">Unread</p>
              <h2 className="text-3xl font-black">
                {data?.unread_count ?? 0}
              </h2>
            </div>
          </div>
        </Card>

        <Card hover={false}>
          <div className="flex items-center gap-4">
            <div className="rounded-2xl bg-success/20 p-3 text-success">
              <CheckCheck className="h-6 w-6" />
            </div>

            <div>
              <p className="text-sm text-gray-400">Status</p>
              <h2 className="text-2xl font-black">Live Alerts</h2>
            </div>
          </div>
        </Card>
      </div>

      <Card hover={false}>
        <div className="mb-6 flex items-center justify-between">
          <div>
            <h2 className="text-2xl font-black">Alert Center</h2>
            <p className="text-sm text-gray-400">
              Notifications generated by your platform and AI modules.
            </p>
          </div>

          <Badge>{notifications.length} items</Badge>
        </div>

        {isLoading ? (
          <div className="space-y-3">
            {[1, 2, 3, 4].map((i) => (
              <div
                key={i}
                className="h-24 animate-pulse rounded-3xl bg-surface/70"
              />
            ))}
          </div>
        ) : notifications.length > 0 ? (
          <div className="space-y-4">
            <AnimatePresence>
              {notifications.map((item) => {
                const Icon = getIcon(item.notification_type)
                const unread = item.is_read === 'false'

                return (
                  <motion.div
                    key={item.id}
                    initial={{ opacity: 0, y: 16 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, x: 40 }}
                    className={`rounded-3xl border p-5 transition ${
                      unread
                        ? 'border-primary/40 bg-primary/10'
                        : 'border-white/10 bg-background/40'
                    }`}
                  >
                    <div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between">
                      <div className="flex gap-4">
                        <div className="rounded-2xl bg-primary/20 p-3 text-primary">
                          <Icon className="h-6 w-6" />
                        </div>

                        <div>
                          <div className="mb-2 flex flex-wrap items-center gap-2">
                            <h3 className="text-lg font-black text-white">
                              {item.title}
                            </h3>

                            <Badge variant={getPriorityVariant(item.priority)}>
                              {item.priority}
                            </Badge>

                            {unread && <Badge>Unread</Badge>}
                          </div>

                          <p className="leading-7 text-gray-400">
                            {item.message}
                          </p>

                          <div className="mt-3 flex flex-wrap gap-2 text-xs text-gray-500">
                            <span>{item.notification_type}</span>
                            <span>•</span>
                            <span>
                              {item.created_at
                                ? new Date(item.created_at).toLocaleString()
                                : 'Unknown time'}
                            </span>
                          </div>
                        </div>
                      </div>

                      <div className="flex gap-2">
                        {unread && (
                          <Button
                            size="sm"
                            variant="secondary"
                            onClick={() => markReadMutation.mutate(item.id)}
                          >
                            <CheckCheck className="h-4 w-4" />
                            Read
                          </Button>
                        )}

                        <Button
                          size="sm"
                          variant="danger"
                          onClick={() => deleteMutation.mutate(item.id)}
                        >
                          <Trash2 className="h-4 w-4" />
                        </Button>
                      </div>
                    </div>
                  </motion.div>
                )
              })}
            </AnimatePresence>
          </div>
        ) : (
          <div className="flex h-72 flex-col items-center justify-center text-center">
            <Bell className="mb-4 h-14 w-14 text-primary" />
            <h2 className="text-2xl font-black">No notifications</h2>
            <p className="mt-2 max-w-md text-gray-400">
              AI alerts, injury warnings, mentorship requests, and system notifications will appear here.
            </p>
          </div>
        )}
      </Card>
    </div>
  )
}