from app.models import (
    Competition,
    Scholarship,
    GovernmentScheme,
    Coach,
    SponsorScout
)


competitions_data = [
    Competition(
        name="Khelo India Youth Games 2026",
        sport="Athletics",
        level="National",
        venue="New Delhi",
        date="2026-07-20",
        registration_fee="Free",
        age_category="Under 18",
        eligibility="State-qualified athletes",
        organizer="Khelo India",
        application_link="https://kheloindia.gov.in",
    ),
    Competition(
        name="National Federation Cup Athletics 2026",
        sport="Athletics",
        level="National",
        venue="Kochi, Kerala",
        date="2026-08-12",
        registration_fee="₹500",
        age_category="Senior",
        eligibility="Federation registered athletes",
        organizer="Athletics Federation of India",
        application_link="https://indianathletics.in",
    ),
    Competition(
        name="South Zone Football Championship 2026",
        sport="Football",
        level="Regional",
        venue="Chennai, Tamil Nadu",
        date="2026-09-05",
        registration_fee="₹1000",
        age_category="Under 19",
        eligibility="District-level players",
        organizer="AIFF South Zone",
        application_link="https://www.the-aiff.com",
    ),
    Competition(
        name="Tamil Nadu State Badminton Open 2026",
        sport="Badminton",
        level="State",
        venue="Coimbatore",
        date="2026-09-18",
        registration_fee="₹750",
        age_category="Under 17",
        eligibility="Registered players",
        organizer="Tamil Nadu Badminton Association",
        application_link="https://badmintonindia.org",
    ),
    Competition(
        name="Junior National Boxing Championship 2026",
        sport="Boxing",
        level="National",
        venue="Bareilly, Uttar Pradesh",
        date="2026-10-10",
        registration_fee="₹600",
        age_category="Under 18",
        eligibility="State-selected athletes",
        organizer="Boxing Federation of India",
        application_link="https://boxingfederation.in",
    ),
    Competition(
        name="Khelo India University Games 2026",
        sport="Multi-Sport",
        level="National",
        venue="Bengaluru",
        date="2026-10-25",
        registration_fee="Free",
        age_category="University Students",
        eligibility="University qualification",
        organizer="Khelo India",
        application_link="https://kheloindia.gov.in",
    ),
    Competition(
        name="National Open Swimming Meet 2026",
        sport="Swimming",
        level="National",
        venue="Hyderabad",
        date="2026-11-08",
        registration_fee="₹500",
        age_category="Senior",
        eligibility="Open qualification",
        organizer="Sports Authority of India",
        application_link="https://sportsauthorityofindia.nic.in",
    ),
    Competition(
        name="Rural Sports Talent Hunt 2026",
        sport="Athletics",
        level="District",
        venue="Madurai",
        date="2026-11-22",
        registration_fee="Free",
        age_category="Under 16",
        eligibility="Open to all rural athletes",
        organizer="Tamil Nadu Sports Authority",
        application_link="https://www.sdat.tn.gov.in",
    ),
    Competition(
        name="Tamil Nadu State Kabaddi Championship 2026",
        sport="Kabaddi",
        level="State",
        venue="Salem",
        date="2026-12-05",
        registration_fee="₹400",
        age_category="Senior",
        eligibility="District players",
        organizer="AKFI",
        application_link="https://akfi.in",
    ),
    Competition(
        name="National Chess Open 2027",
        sport="Chess",
        level="National",
        venue="Mumbai",
        date="2027-01-12",
        registration_fee="₹1200",
        age_category="Open",
        eligibility="FIDE registered players",
        organizer="AICF",
        application_link="https://aicf.in",
    ),
    Competition(
        name="Inter-District Volleyball League 2027",
        sport="Volleyball",
        level="District",
        venue="Tiruchirapalli",
        date="2027-01-28",
        registration_fee="₹350",
        age_category="Under 21",
        eligibility="District clubs",
        organizer="Tamil Nadu Volleyball Association",
        application_link="https://tnva.in",
    ),
    Competition(
        name="National Wrestling Trials 2027",
        sport="Wrestling",
        level="National",
        venue="Lucknow",
        date="2027-02-14",
        registration_fee="₹700",
        age_category="Senior",
        eligibility="Federation approval",
        organizer="Wrestling Federation of India",
        application_link="https://wfiindia.com",
    ),
    Competition(
        name="State Hockey Selection Camp 2027",
        sport="Hockey",
        level="State",
        venue="Erode",
        date="2027-03-02",
        registration_fee="₹300",
        age_category="Under 19",
        eligibility="School and academy players",
        organizer="Hockey India",
        application_link="https://www.hockeyindia.org",
    ),
    Competition(
        name="Inter-School Basketball Championship 2027",
        sport="Basketball",
        level="District",
        venue="Chennai",
        date="2027-03-20",
        registration_fee="₹250",
        age_category="Under 17",
        eligibility="School teams",
        organizer="Tamil Nadu Basketball Association",
        application_link="https://tnba.in",
    ),
    Competition(
        name="National Table Tennis Ranking Tournament 2027",
        sport="Table Tennis",
        level="National",
        venue="Pune",
        date="2027-04-08",
        registration_fee="₹800",
        age_category="Junior",
        eligibility="State-ranked players",
        organizer="TTFI",
        application_link="https://ttfi.org",
    ),
    Competition(
        name="South India Junior Athletics League 2027",
        sport="Athletics",
        level="Regional",
        venue="Bengaluru",
        date="2027-04-25",
        registration_fee="₹450",
        age_category="Under 20",
        eligibility="District and state athletes",
        organizer="South India Athletics Council",
        application_link="https://indianathletics.in",
    ),
    Competition(
        name="Tamil Nadu Football Talent Trials 2027",
        sport="Football",
        level="State",
        venue="Madurai",
        date="2027-05-14",
        registration_fee="Free",
        age_category="Under 19",
        eligibility="Open trials for academy players",
        organizer="Tamil Nadu Football Association",
        application_link="https://www.the-aiff.com",
    ),
    Competition(
        name="National Youth Weightlifting Championship 2027",
        sport="Weightlifting",
        level="National",
        venue="Patiala",
        date="2027-06-04",
        registration_fee="₹650",
        age_category="Under 21",
        eligibility="State-selected lifters",
        organizer="Indian Weightlifting Federation",
        application_link="https://iwlf.in",
    ),
    Competition(
        name="All India University Cricket Cup 2027",
        sport="Cricket",
        level="National",
        venue="Bengaluru",
        date="2027-06-22",
        registration_fee="₹1000",
        age_category="University Students",
        eligibility="University team players",
        organizer="AIU Sports",
        application_link="https://aiu.ac.in",
    ),
    Competition(
        name="National Para Sports Talent Meet 2027",
        sport="Para Sports",
        level="National",
        venue="New Delhi",
        date="2027-07-10",
        registration_fee="Free",
        age_category="Open",
        eligibility="Para athletes with valid classification",
        organizer="Paralympic Committee of India",
        application_link="https://www.paralympicindia.org.in",
    ),
]


scholarships_data = [
    Scholarship(
        name="Khelo India Athlete Scholarship 2026",
        provider="Khelo India",
        amount="₹6.28 lakh/year",
        sport_eligibility="Multi-Sport",
        age_category="15-29",
        eligibility_criteria="Khelo India selected athletes",
        application_link="https://kheloindia.gov.in",
        deadline="2026-08-31",
    ),
    Scholarship(
        name="TOPS Development Group Support 2026",
        provider="MYAS",
        amount="Monthly assistance + training support",
        sport_eligibility="Olympic Sports",
        age_category="Open",
        eligibility_criteria="National elite and development athletes",
        application_link="https://yas.nic.in",
        deadline="2026-09-30",
    ),
    Scholarship(
        name="Reliance Foundation Sports Scholarship 2026",
        provider="Reliance Foundation",
        amount="Training and education support",
        sport_eligibility="Football, Athletics, Archery",
        age_category="Under 21",
        eligibility_criteria="Talent-based selection",
        application_link="https://reliancefoundation.org",
        deadline="2026-10-15",
    ),
    Scholarship(
        name="JSW Sports Excellence Programme 2026",
        provider="JSW Sports",
        amount="Training + Funding",
        sport_eligibility="Multi-Sport",
        age_category="Open",
        eligibility_criteria="State/National-level athletes",
        application_link="https://jsw.in/sports",
        deadline="2026-11-10",
    ),
    Scholarship(
        name="Amity Sports Scholarship 2027",
        provider="Amity University",
        amount="25%-100% Tuition Waiver",
        sport_eligibility="Multi-Sport",
        age_category="University",
        eligibility_criteria="Medal winners and sports quota candidates",
        application_link="https://amity.edu",
        deadline="2027-01-20",
    ),
    Scholarship(
        name="SRM Sports Quota Scholarship 2027",
        provider="SRM University",
        amount="Tuition Waiver",
        sport_eligibility="Hockey, Football, Basketball, Athletics",
        age_category="University",
        eligibility_criteria="Sports achievements",
        application_link="https://srmist.edu.in",
        deadline="2027-02-15",
    ),
    Scholarship(
        name="Tata Trusts Sports Support 2027",
        provider="Tata Trusts",
        amount="Variable Support",
        sport_eligibility="Wrestling, Archery, Athletics",
        age_category="Open",
        eligibility_criteria="Talent-based financial need",
        application_link="https://tatatrusts.org",
        deadline="2027-03-01",
    ),
    Scholarship(
        name="SAI NSTC Scholarship 2027",
        provider="SAI",
        amount="Residential Training Support",
        sport_eligibility="Multi-Sport",
        age_category="10-18",
        eligibility_criteria="Selected athletes through SAI centres",
        application_link="https://sportsauthorityofindia.nic.in",
        deadline="2027-03-30",
    ),
    Scholarship(
        name="Anna University Sports Quota Support 2027",
        provider="Anna University",
        amount="Admission Support",
        sport_eligibility="Multi-Sport",
        age_category="University",
        eligibility_criteria="Sports quota eligibility",
        application_link="https://annauniv.edu",
        deadline="2027-05-15",
    ),
    Scholarship(
        name="Tamil Nadu Elite Athlete Support Scheme 2027",
        provider="SDAT Tamil Nadu",
        amount="Training and competition support",
        sport_eligibility="Multi-Sport",
        age_category="Open",
        eligibility_criteria="Tamil Nadu state and national athletes",
        application_link="https://www.sdat.tn.gov.in",
        deadline="2027-06-30",
    ),
]



schemes_data = [
    GovernmentScheme(name="Khelo India Scheme", authority="Ministry of Sports", benefits="Scholarship + Training", eligibility="Youth athletes", official_website="https://kheloindia.gov.in"),
    GovernmentScheme(name="TOPS", authority="MYAS", benefits="International support", eligibility="Elite athletes", official_website="https://yas.nic.in"),
    GovernmentScheme(name="SAI Training Centres", authority="SAI", benefits="Training + Hostel", eligibility="10-18 years", official_website="https://sportsauthorityofindia.nic.in"),
    GovernmentScheme(name="National Sports Talent Contest", authority="SAI", benefits="Residential training", eligibility="Young athletes", official_website="https://sportsauthorityofindia.nic.in"),
    GovernmentScheme(name="PDUNWFS", authority="MYAS", benefits="Financial aid", eligibility="Retired athletes", official_website="https://yas.nic.in"),
    GovernmentScheme(name="National Sports Policy 2025", authority="Government of India", benefits="Sports development", eligibility="All athletes", official_website="https://yas.nic.in"),
    GovernmentScheme(name="Tamil Nadu Sports Quota", authority="SDAT Tamil Nadu", benefits="Admission support", eligibility="State athletes", official_website="https://www.sdat.tn.gov.in"),
    GovernmentScheme(name="Fit India Movement Support", authority="Government of India", benefits="Fitness awareness and events", eligibility="Schools, colleges, athletes", official_website="https://fitindia.gov.in"),
]

coaches_data = [
    Coach(name="Rajesh Kumar", sport="Athletics", location="Chennai", experience="10 Years", certification="NIS Certified", contact="rajeshcoach@gmail.com"),
    Coach(name="Priya Sharma", sport="Badminton", location="Bengaluru", experience="7 Years", certification="BAI Certified", contact="priya.badminton@gmail.com"),
    Coach(name="Manoj Singh", sport="Boxing", location="Delhi", experience="12 Years", certification="National Coach", contact="manojboxing@gmail.com"),
    Coach(name="Aravind R", sport="Football", location="Coimbatore", experience="6 Years", certification="AIFF D License", contact="aravindfootball@gmail.com"),
    Coach(name="Karthik M", sport="Kabaddi", location="Salem", experience="8 Years", certification="State Certified", contact="karthikkabaddi@gmail.com"),
    Coach(name="Vivek Joshi", sport="Swimming", location="Hyderabad", experience="9 Years", certification="SAI Certified", contact="vivekswim@gmail.com"),
    Coach(name="Meena Ravi", sport="Basketball", location="Chennai", experience="5 Years", certification="State Coach", contact="meenabasketball@gmail.com"),
    Coach(name="Suresh Babu", sport="Volleyball", location="Tiruchirapalli", experience="11 Years", certification="National Level Trainer", contact="sureshvolleyball@gmail.com"),
    Coach(name="Anita Das", sport="Table Tennis", location="Pune", experience="6 Years", certification="TTFI Certified", contact="anitatt@gmail.com"),
    Coach(name="Ramesh Iyer", sport="Hockey", location="Erode", experience="13 Years", certification="Hockey India Certified", contact="rameshhockey@gmail.com"),
]

sponsors_scouts_data = [
    SponsorScout(organization="JSW Sports", focus_sports="Multi-Sport", support_type="Scholarships + Training", website="https://jsw.in/sports"),
    SponsorScout(organization="Reliance Foundation", focus_sports="Football, Athletics", support_type="Sponsorship + Training", website="https://reliancefoundation.org"),
    SponsorScout(organization="Tata Trusts", focus_sports="Wrestling, Archery", support_type="CSR Sports Support", website="https://tatatrusts.org"),
    SponsorScout(organization="Olympic Gold Quest", focus_sports="Olympic Sports", support_type="Elite Athlete Support", website="https://olympicgoldquest.in"),
    SponsorScout(organization="GoSports Foundation", focus_sports="Emerging Sports", support_type="Mentorship + Funding", website="https://gosportsfoundation.in"),
    SponsorScout(organization="Inspire Institute of Sport", focus_sports="Multi-Sport", support_type="Residential Training", website="https://inspireinstituteofsport.com"),
    SponsorScout(organization="Dream Sports Foundation", focus_sports="Grassroots Sports", support_type="Rural Sports Development", website="https://dreamsports.foundation"),
    SponsorScout(organization="Sports Authority Scout Network", focus_sports="Multi-Sport", support_type="Talent Identification", website="https://sportsauthorityofindia.nic.in"),
]
